wix-incubator/bubanai

package.json

- set the `main` and `types` values in the `package.json`

Specify where to import from

---

.github/workflows/deploy-pages.yml
.github/workflows/main.yml
.github/workflows/version.yml

- add the GitHub action flow to increment the package version, create a new tag and create automatically create a release

Add GitHub action to create a new release

---

src/element/actions/click.ts
src/element/actions/getValue.ts
src/element/evaluateOnSelectorOrElement.ts
src/element/getAttribute.ts
src/element/getElement.ts
src/element/getProperty.ts
src/element/states/getClasses.ts
src/element/states/isDisabled.ts
src/index.ts
tests/element/actions/click.spec.ts
tests/element/actions/getValue.spec.ts
tests/element/states/isDisabled.spec.ts
typedoc.json

- added basic element interaction method `getValue`, updated `click` method
- added element state methods to get attribute and property values
- in the `typedoc.json` added `puppeteer` entry point in order to have links in the API documentation to the appropriate interfaces

Add basic element interaction methods

---

package.json
src/element/evaluateOnSelectorOrElement.ts
yarn.lock

- downgrade the Puppeteer package in order to be complied with Sled

Downgrade pptr package

---

package.json
src/element/waits/waitForElement.ts
src/element/waits/waitToBeInViewport.ts
src/element/waits/waitToBeNotVisible.ts
src/element/waits/waitToBeVisible.ts
src/index.ts
tests/element/wait/waitToBeInViewport.spec.ts
tests/element/wait/waitToBeNotVisible.spec.ts
tests/element/wait/waitToBeVisible.spec.ts
typedoc.json

- Add basic element wait: `waitToBeInViewport`, `waitToBeNotVisible`, `waitToBeVisible`

Add basic element waits

---

tsconfig.json

- Update the `module` value in the `tsconfig` to fix the error message `Jest encountered an unexpected token`

Update module value in the tsconfig

---

src/index.ts

- export additional methods to find element(s)

Export find elements method

---

README.md

Update documentation with section how to install and use the library

chore: Add doc how to install and use the lib

---

README.md
tests/element/actions/type.spec.ts

- Update the main description
- Add more examples of the library usage
- Add `FAQ` section

chore(docs): Add more examples to the documentation

---

src/element/states/isVisible.ts
tests/element/states/isVisible.spec.ts

Found another issue in the same isVisible function

Fix issue in isVisible function

---

src/assert/index.ts
src/assert/isEqualAsync.ts
src/collection/async/eachAsync.ts
src/collection/index.ts
src/date/dateUtils.ts
src/date/index.ts
src/date/types.ts
src/index.ts

add date, some collection and assert utils

---

src/boundingBox/getCenter.ts
src/boundingBox/getOffsetToCenter.ts
src/boundingBox/index.ts
src/boundingBox/types.ts
src/drag/dragBy.ts
src/drag/dragElementBy.ts
src/drag/dragTo.ts
src/drag/index.ts
src/drag/moveToCoordinantes.ts
src/drag/types.ts
src/error/index.ts
src/error/throwTestError.ts
src/index.ts
src/waitFor.ts
src/waits/index.ts
src/waits/waitForValueToStopChanging.ts

add drag, wait utils, error utils

---

src/drag/dragElementToElement.ts
src/drag/dragElementToPoint.ts
src/drag/dragTo.ts
src/drag/index.ts
src/drag/types.ts

add some drag utils

---

src/collection/async/createPromiseChain.ts
src/collection/index.ts
src/index.ts
src/network/index.ts
src/network/requestWaiter.ts
src/network/types.ts
src/network/waitForNetworkIdle.ts

add network utils

---

src/console/index.ts
src/console/localStorage.ts
src/index.ts
src/keyboard/index.ts
src/keyboard/keyboard.ts
src/keyboard/types.ts
src/page/index.ts
src/page/types.ts
src/waits/index.ts
src/waits/waitForAnimation.ts

add animation and keyboard utils

---

src/console/getCopiedText.ts
src/console/index.ts

add get copied text

---

src/error/throwTestError.ts
src/frame/getFramesInContext.ts
src/frame/index.ts
src/frame/search/getFrameByName.ts
src/frame/search/getFrameByUrl.ts
src/frame/search/getIframeBySelector.ts
src/frame/search/getIframeByTitle.ts
src/frame/types.ts
src/page/actions/waitForTab.ts
src/page/index.ts
src/settings.ts
src/waits/index.ts
src/waits/types.ts
src/waits/waitWithAttempts.ts

add frame and page utils

---

src/element/index.ts
src/element/types.ts
src/element/waits/waitForScopedSelector.ts

add wait for scoped selector

---

src/element/baseDrivers/elementBaseDriver.ts
src/element/baseDrivers/internalElementBaseDriver.ts
src/element/index.ts

add internal element base driver

---

README.md

fix installation guide

---

src/waits/index.ts
src/waits/waitForCondition.ts

add wfc for simply migration to lib

---

src/waits/index.ts

add export

---

package.json

upgrade major version

---

src/drag/dragBy.ts
src/frame/search/getFrameByUrl.ts
src/page/actions/waitForTab.ts
src/types.ts

change to correct type

---

src/drag/dragTo.ts
src/drag/moveToCoordinantes.ts
src/drag/types.ts

add steps to drag

---

src/element/baseDrivers/internalElementBaseDriver.ts
src/element/waits/waitToBeNotVisible.ts

make wait to be not visible to accept ElementHandle

---

src/assert/isEqualAsync.ts
src/boundingBox/floorBoundingValues.ts
src/boundingBox/getBottom.ts
src/boundingBox/getBoundingBox.ts
src/boundingBox/getCenter.ts
src/boundingBox/getElementVisibleBoundingBox.ts
src/boundingBox/getFrameBoundingBox.ts
src/boundingBox/getOffsetToCenter.ts
src/boundingBox/getPointByDimensionDivider.ts
src/boundingBox/getRight.ts
src/boundingBox/getSnugBoundingBox.ts
src/boundingBox/getX.ts
src/boundingBox/getY.ts
src/boundingBox/isInCenterOfContainer.ts
src/boundingBox/isOffsetBy.ts
src/boundingBox/isPlacedInside.ts
src/boundingBox/waitForBoundingToBePlacedInside.ts
src/collection/async/createPromiseChain.ts
src/collection/async/eachAsync.ts
src/collection/async/filterAsync.ts
src/collection/async/findAsync.ts
src/collection/async/mapAsync.ts
src/collection/search/getElementFromArrayByContainingText.ts
src/collection/search/getElementFromArrayByText.ts
src/collection/search/getElementIndexByContainingText.ts
src/collection/search/getElementIndexByProperty.ts
src/collection/search/getElementIndexByText.ts
src/collection/search/getElementsTextsFromArray.ts

add methods descriptions 1

---

src/dropdown/getDropdownOptionBySelector.ts
src/dropdown/getDropdownOptionByTextExactMatch.ts
src/dropdown/getDropdownOptionByValue.ts
src/dropdown/getDropdownOptions.ts
src/dropdown/getDropdownOptionsAttribute.ts
src/dropdown/isDropdownOptionAvailableByValue.ts
src/dropdown/isDropdownOptionExistByValue.ts
src/dropdown/openDropdown.ts
src/dropdown/selectDropdownOptionByContainingText.ts
src/dropdown/selectDropdownOptionByContainingValue.ts
src/dropdown/selectDropdownOptionByIndex.ts
src/dropdown/selectDropdownOptionBySelector.ts
src/dropdown/selectDropdownOptionByTextExactMatch.ts
src/dropdown/selectDropdownOptionByValue.ts
src/dropdown/selectOptionByIndex.ts

add dropdown descriptions

---

src/element/evaluateOnSelectorOrElement.ts
src/element/getAttribute.ts
src/element/getComputedStyle.ts
src/element/getElement.ts
src/element/getElements.ts
src/element/getParent.ts
src/element/getProperty.ts
src/element/waits/waitForAttributeToBeChanged.ts
src/element/waits/waitForElement.ts
src/element/waits/waitForElementAttributeToStopChanging.ts
src/element/waits/waitForElementNotToBeInViewport.ts
src/element/waits/waitForElementNotToHaveAttribute.ts
src/element/waits/waitForElementPositionToBeStale.ts
src/element/waits/waitForElementToBeChecked.ts
src/element/waits/waitForElementToBeExpanded.ts
src/element/waits/waitForElementToBeNotDisabled.ts
src/element/waits/waitForElementToBeUnChecked.ts
src/element/waits/waitForElementToContainClass.ts
src/element/waits/waitForElementToContainText.ts
src/element/waits/waitForElementToHaveAttribute.ts
src/element/waits/waitForElementToHaveAttributePart.ts
src/element/waits/waitForElementToHaveText.ts
src/element/waits/waitForScopedSelector.ts
typedoc.json

add element descriptions 2

---

src/error/throwTestError.ts
src/frame/getFramesInContext.ts
src/frame/search/getFrameBySelector.ts
src/frame/search/getFrameByTitle.ts
src/frame/search/getFrameByUrl.ts
src/frame/waitForFrameToBeDetached.ts

add description for frames

---

README.md

Noticed this during the demo 😅

fix license shield
